/**
 * author : Felipe Alfonso
 * date : 03-10-13.
 * version : 1.0
 * about : Small ASCII Engine.
 *
 */
"use strict";
window.ps=window.ps||{};
(function(d){d.millisecs=function(){return(new Date).getTime()};d.random=function(b,a){return Math.floor(Math.random()*(a-b+1)+b)};d.ASCIIColors={BLACK:0,DARK_GREY:1,DARK_MID_GREY:2,GREY:3,LIGHT_MID_GREY:4,LIGHT_GREY:5,WHITE:6,TRANSPARENT:7,colorTransform:{0:"@",1:"#",2:"W",3:"+",4:";",5:":",6:"\u00b7",7:" "},colorTransformInvert:{0:" ",1:"\u00b7",2:":",3:";",4:"+",5:"W",6:"#",7:"@"},RGBAToASCII:function(b){if(4==b.length){var a=0,c=1785;if(0==b[3])return d.ASCIIColors.TRANSPARENT;for(var e=0;e<b.length;e++)a+=
	b[e];if(a<=Math.floor(c/7))return d.ASCIIColors.BLACK;if(a>Math.floor(c/7)&&a<=Math.floor(c/6))return d.ASCIIColors.DARK_GREY;if(a>Math.floor(c/6)&&a<=Math.floor(c/5))return d.ASCIIColors.DARK_MID_GREY;if(a>Math.floor(c/5)&&a<=Math.floor(c/4))return d.ASCIIColors.GREY;if(a>Math.floor(c/4)&&a<=Math.floor(c/3))return d.ASCIIColors.LIGHT_MID_GREY;if(a>Math.floor(c/3)&&a<=Math.floor(c/2))return d.ASCIIColors.LIGHT_GREY;if(a>Math.floor(c/2)&&a<=c)return d.ASCIIColors.WHITE}else if(3==b.length){a=0;c=1275;
	for(e=0;e<b.length;e++)a+=b[e];if(a<=Math.floor(c/7))return d.ASCIIColors.BLACK;if(a>Math.floor(c/7)&&a<=Math.floor(c/6))return d.ASCIIColors.DARK_GREY;if(a>Math.floor(c/6)&&a<=Math.floor(c/5))return d.ASCIIColors.DARK_MID_GREY;if(a>Math.floor(c/5)&&a<=Math.floor(c/4))return d.ASCIIColors.GREY;if(a>Math.floor(c/4)&&a<=Math.floor(c/3))return d.ASCIIColors.LIGHT_MID_GREY;if(a>Math.floor(c/3)&&a<=Math.floor(c/2))return d.ASCIIColors.LIGHT_GREY;if(a>Math.floor(c/2)&&a<=c)return d.ASCIIColors.WHITE}else return d.ASCIIColors.TRANSPARENT},
	contextToASCII:function(b){var a=[],c=null;try{c=b.getImageData(0,0,b.canvas.width,b.canvas.height).data}catch(e){return[[0]]}for(var f=0,l=0;l<b.canvas.height;l++){for(var h=[],k=0;k<b.canvas.width;k++){for(var g=[],n=0;4>n;n++)g[g.length]=c[f],f++;h[h.length]=d.ASCIIColors.RGBAToASCII(g)}a[a.length]=h}return a}};d.ASCIIText={fontHeight:4,fontWidth:5,letterSpacing:1,a:[[7,0,0,7],[0,7,7,0],[0,0,0,0],[0,7,7,0]],b:[[0,0,0,7],[0,0,0,7],[0,7,7,0],[0,0,0,7]],c:[[7,0,0,0],[0,7,7,7],[0,7,7,7],[7,0,0,0]],
	d:[[0,0,0,7],[0,7,7,0],[0,7,7,0],[0,0,0,7]],e:[[0,0,0,0],[0,0,0,7],[0,7,7,7],[0,0,0,0]],f:[[0,0,0,0],[0,7,7,7],[0,0,0,7],[0,7,7,7]],g:[[7,0,0,0],[0,7,7,7],[0,7,0,0],[7,0,0,0]],h:[[0,7,7,0],[0,0,0,0],[0,7,7,0],[0,7,7,0]],i:[[0,0,0,0],[7,0,0,7],[7,0,0,7],[0,0,0,0]],j:[[7,7,7,0],[7,7,7,0],[0,7,7,0],[7,0,0,7]],k:[[0,7,7,0],[0,0,0,7],[0,7,0,7],[0,7,7,0]],l:[[0,7,7,7],[0,7,7,7],[0,7,7,7],[0,0,0,0]],m:[[0,7,7,0],[0,0,0,0],[0,7,0,0],[0,7,7,0]],n:[[0,7,7,0],[0,0,7,0],[0,7,0,0],[0,7,7,0]],o:[[7,0,0,7],[0,7,
		7,0],[0,7,7,0],[7,0,0,7]],p:[[0,0,0,7],[0,7,7,0],[0,0,0,7],[0,7,7,7]],q:[[7,0,0,7],[0,7,7,0],[0,7,0,0],[7,0,0,0]],r:[[0,0,0,7],[0,7,7,0],[0,0,0,7],[0,7,7,0]],s:[[7,0,0,0],[0,0,0,7],[7,7,7,0],[0,0,0,7]],t:[[0,0,0,0],[7,0,0,7],[7,0,0,7],[7,0,0,7]],u:[[0,7,7,0],[0,7,7,0],[0,7,7,0],[7,0,0,7]],v:[[0,7,7,0],[0,7,7,0],[7,0,7,0],[7,7,0,7]],w:[[0,7,7,0],[0,7,7,0],[0,7,0,0],[7,0,7,0]],y:[[0,7,7,0],[7,0,0,7],[7,0,0,7],[7,0,0,7]],z:[[0,0,0,0],[7,7,0,7],[7,0,7,7],[0,0,0,0]],1:[[7,0,0,7],[7,7,0,7],[7,7,0,7],[7,
		7,0,7]],2:[[7,0,0,7],[0,7,7,0],[7,0,0,7],[0,0,0,0]],3:[[7,7,7,7],[7,7,7,7],[7,7,7,7],[7,7,7,7]],4:[[0,0,0,7],[7,0,0,0],[7,7,7,0],[0,0,0,7]],5:[[0,0,0,0],[0,0,0,7],[7,7,7,0],[0,0,0,7]],6:[[7,0,0,0],[0,7,7,7],[0,0,0,0],[7,0,0,7]],7:[[0,0,0,0],[7,7,7,0],[7,7,0,7],[7,0,7,7]],8:[[7,0,0,7],[0,0,0,0],[0,0,0,0],[7,0,0,7]],9:[[7,0,0,0],[0,7,7,0],[7,0,0,0],[7,7,7,0]],0:[[7,0,0,7],[0,7,7,0],[0,7,7,0],[7,0,0,7]],drawText:function(b,a,c){for(var e=0;e<b.length;e++){var f=d.ASCIIText.fontWidth+d.ASCIIText.letterSpacing;
		d.ASCIIText[b[e].toLowerCase()]&&d.ASCIIDisplay.drawBitmap(d.ASCIIText[b[e].toLowerCase()],a+e*f,c)}},textWidth:function(b){return(d.ASCIIText.fontWidth+d.ASCIIText.letterSpacing)*b.length}};var m,g;d.ASCIIDisplay={invert:!1,width:0,height:0,createDisplay:function(b,a,c){c=c||10;d.ASCIIDisplay.width=b;d.ASCIIDisplay.height=a;m=document.createElement("pre");m.style.letterSpacing="4px";m.style.fontSize=c+"px";g=[];for(c=0;c<a;c++){for(var e=[],f=0;f<b;f++)e[e.length]=d.ASCIIColors.TRANSPARENT;g[g.length]=
	e}document.body.appendChild(m)},clearScreen:function(b){if(g&&m){if(void 0==b||null==b)b=d.ASCIIColors.TRANSPARENT;b=parseInt(b);g.splice(0,g.length);for(var a=0;a<d.ASCIIDisplay.height;a++){for(var c=[],e=0;e<d.ASCIIDisplay.width;e++)c[c.length]=b;g[g.length]=c}}else throw Error("ASCII Display must be set first with ASCIIDisplay.createDisplay");},drawPixel:function(b,a,c){if(g&&m){if(0<=Math.floor(b)&&0<=Math.floor(a)&&Math.floor(b)<d.ASCIIDisplay.width-1&&Math.floor(a)<d.ASCIIDisplay.height-1)for(var e=
	0;e<d.ASCIIDisplay.height;e++)for(var f=0;f<d.ASCIIDisplay.width;f++)if(Math.floor(f)==Math.floor(b)&&Math.floor(e)==Math.floor(a)&&7!=c){g[Math.floor(e)][Math.floor(f)]=c;return}}else throw Error("ASCII Display must be set first with ASCIIDisplay.createDisplay");},drawRect:function(b,a,c,e,f){var l=[];f=f||0;for(var h=0;h<e;h++){for(var k=[],g=0;g<c;g++)k[k.length]=f;l[l.length]=k}d.ASCIIDisplay.drawBitmap(l,b,a)},drawLine:function(b,a,c,e,f){f=f||0;var l,h,k,g,n,p,m;l=Math.abs(c-b);h=Math.abs(e-
	a);k=b;g=a;c=c>=b?b=1:b=-1;e=e>=a?a=1:a=-1;l>=h?(e=b=0,n=l,p=l/2,m=h):(a=c=0,n=h,p=h/2,m=l,l=h);for(h=0;h<=l;h++)d.ASCIIDisplay.drawPixel(k,g,f),p+=m,p>=n&&(p-=n,k+=b,g+=a),k+=c,g+=e},drawBitmap:function(b,a,c){if(g&&m)for(var e=0;e<b.length;e++)for(var f=0;f<b[e].length;f++)d.ASCIIDisplay.drawPixel(a+f,c+e,b[e][f]);else throw Error("ASCII Display must be set first with ASCIIDisplay.createDisplay");},drawClippedBitmap:function(b,a,c,e,f,l,h){if(g&&m){f=f||0;l=l||0;h=h||0;e=parseInt(e||0);f=parseInt(f);
	l=parseInt(l);h=parseInt(h);if(0>e||0>f||f+h>b.length||null==b[0]||void 0==b[0]||e+l>b[0].length)throw Error("Clip area is out of bitmap array");for(var k=[],q=f;q<f+h;q++){for(var n=[],p=e;p<e+l;p++)n[n.length]=b[q][p];k[k.length]=n}d.ASCIIDisplay.drawBitmap(k,a,c)}else throw Error("ASCII Display must be set first with ASCIIDisplay.createDisplay");},flush:function(){if(g&&m){for(var b="",a=0;a<g.length-1;a++){for(var c=0;c<g[a].length-1;c++)b+=d.ASCIIDisplay.invert?d.ASCIIColors.colorTransformInvert[g[a][c]]:
	d.ASCIIColors.colorTransform[g[a][c]];b+="\n"}m.innerHTML=b}else throw Error("ASCII Display must be set first with ASCIIDisplay.createDisplay");}};d.ASCIISprite=function(b,a,c,e){this.x=b||0;this.y=a||0;this.loaded=!1;this.bitmapData=null;this.height=this.width=0;this.animation={};this.currentAnimation=null;this.frame=this.animationIndex=0;this.frameRate=25;this.frameCounter=0;this.isAnimated=!1;this.currentAnimationName="";this.clip={x:0,y:0,width:0,height:0};var f=new Image,g=document.createElement("canvas"),
	h=null,k=this;f.onload=function(){g.width=f.width;g.height=f.height;k.width=f.width;k.height=f.height;k.clip.width=f.width;k.clip.height=f.height;h=g.getContext("2d");h.drawImage(f,0,0);k.bitmapData=d.ASCIIColors.contextToASCII(h);k.loaded=!0;f.onload=null;"function"==typeof e&&e(k)};f.src=c};d.ASCIISprite.prototype={makeFrames:function(b,a){this.clip.width=b;this.clip.height=a;this.width=b;this.height=a;this.frame=0;this.isAnimated=!0},addAnimation:function(b,a){if(void 0!=a.length)this.animation[b]=
	a;else throw Error("No frames set");},play:function(b,a){if(void 0!=this.animation[b]&&null!=this.animation[b])this.currentAnimationName!=b&&(this.frameRate=a||this.frameRate,this.currentAnimation=this.animation[b],this.animationIndex=0,this.currentAnimationName=b);else throw Error("No animation exists with the name "+b);},update:function(){this.loaded&&this.isAnimated&&null!=this.currentAnimation&&d.millisecs()-this.frameCounter>1E3/this.frameRate&&(this.frame=this.currentAnimation[this.animationIndex],
	this.frameCounter=d.millisecs(),this.animationIndex++,this.animationIndex>this.currentAnimation.length-1&&(this.animationIndex=0))},render:function(){this.loaded&&(this.isAnimated?null!=this.bitmapData&&(this.clip.x=this.clip.width*this.frame,d.ASCIIDisplay.drawClippedBitmap(this.bitmapData,this.x,this.y,this.clip.x,0,this.clip.width,this.clip.height)):null!=this.bitmapData&&d.ASCIIDisplay.drawBitmap(this.bitmapData,this.x,this.y))}}})(ps);
